### ISSUE TITLE
techdebt(mypy): unused type-ignore comments in src/app/services/token.py

### ISSUE THREAD

**Issue by parametrization** [noorinalabs/noorinalabs-user-service#76]
`make typecheck` reports two errors on `main`:

```
src/app/services/token.py:43: error: Unused "type: ignore" comment  [unused-ignore]
src/app/services/token.py:57: error: Unused "type: ignore" comment  [unused-ignore]
Found 2 errors in 1 file (checked 44 source files)
```

Pre-existing — not introduced by #135. Surfaced while running `make check` for the OAUTH_PROVIDER_BASE_URL_OVERRIDE PR (noorinalabs-main#135). Likely fallout from a `python-jose` type-stub upgrade that made earlier ignores redundant.

Fix: remove the two `# type: ignore[...]` comments and rerun `make typecheck` to confirm clean.

Scope: small, mechanical. Can be picked up by anyone on the user-service team.
